export const monitorItems = [
  {
    id: 1,
    title: 'File Encryption',
    color: 'bg-[#FFD600]',
    text: 'AES_GCM',
    detail: 'Encrypt selected files locally before anything leaves the browser.',
    x: '8%',
    y: '35%',
    size: { w: 'clamp(180px, 23vw, 280px)', h: 'clamp(150px, 18vw, 200px)' },
    mobile: { w: '40vw', h: '136px', x: '5%', y: '22%' },
  },
  {
    id: 2,
    title: 'Rhythm Timing',
    color: 'bg-[#00E676]',
    text: 'TIMING',
    detail: 'Capture note intervals and hold patterns as part of the secret.',
    x: '63%',
    y: '14%',
    size: { w: 'clamp(165px, 17vw, 200px)', h: 'clamp(140px, 15vw, 170px)' },
    mobile: { w: '36vw', h: '126px', x: '57%', y: '18%' },
  },
  {
    id: 3,
    title: 'Melody Secret',
    color: 'bg-[#FF4D4D]',
    text: 'NOTES',
    detail: 'Use the sequence you remember as the basis for key derivation.',
    x: '28%',
    y: '48%',
    size: { w: 'clamp(165px, 17vw, 200px)', h: 'clamp(150px, 18vw, 200px)' },
    mobile: { w: '37vw', h: '136px', x: '7%', y: '42%' },
  },
  {
    id: 4,
    title: 'Vault Metadata',
    color: 'bg-[#FF4D4D]',
    text: 'META',
    detail: 'Store filenames, timestamps, and status without raw secrets.',
    x: '68%',
    y: '38%',
    size: { w: 'clamp(160px, 16vw, 190px)', h: 'clamp(145px, 17vw, 190px)' },
    mobile: { w: '38vw', h: '132px', x: '55%', y: '41%' },
  },
  {
    id: 5,
    title: 'Wrong Melody Rejection',
    color: 'bg-[#FFD600]',
    text: 'DENY',
    detail: 'Authenticated decryption fails when the melody material is wrong.',
    x: '45%',
    y: '66%',
    size: { w: 'clamp(220px, 27vw, 320px)', h: 'clamp(125px, 12vw, 140px)' },
    mobile: { w: '78vw', h: '116px', x: '11%', y: '62%' },
  },
  {
    id: 6,
    title: 'Key Derivation',
    color: 'bg-white',
    text: 'KDF_v1',
    detail: 'Convert canonical melody data into AES-ready key material.',
    x: '43%',
    y: '38%',
    size: { w: 'clamp(170px, 18vw, 220px)', h: 'clamp(120px, 12vw, 140px)' },
    mobile: { w: '36vw', h: '116px', x: '31%', y: '31%' },
  },
  {
    id: 7,
    title: 'Vault Artifact',
    color: 'bg-[#00E676]',
    text: '.VAULT',
    detail: 'Export encrypted files as portable vault containers.',
    x: '72%',
    y: '62%',
    size: { w: 'clamp(165px, 18vw, 230px)', h: 'clamp(125px, 13vw, 150px)' },
    mobile: { w: '38vw', h: '122px', x: '55%', y: '78%' },
  },
  {
    id: 8,
    title: 'Private by Design',
    color: 'bg-white',
    text: 'ENCRYPTED',
    detail: 'Avoid storing plaintext files, raw melodies, or derived keys.',
    x: '5%',
    y: '65%',
    size: { w: 'clamp(170px, 18vw, 210px)', h: 'clamp(120px, 12vw, 140px)' },
    mobile: { w: '38vw', h: '122px', x: '7%', y: '78%' },
  },
];

export const howItWorksContent = {
  eyebrow: 'VAULT FLOW',
  title: 'How It Works',
  steps: [
    {
      id: 'select',
      label: '01',
      title: 'Select File',
      copy: 'Choose the file that should become a protected .vault artifact.',
      metric: 'FILE',
    },
    {
      id: 'melody',
      label: '02',
      title: 'Capture Melody',
      copy: 'Record note order and timing intervals from virtual piano input.',
      metric: 'NOTES',
    },
    {
      id: 'derive',
      label: '03',
      title: 'Derive Key',
      copy: 'Serialize the pattern deterministically and derive AES key material.',
      metric: 'KDF',
    },
    {
      id: 'export',
      label: '04',
      title: 'Export Vault',
      copy: 'Encrypt locally, download the .vault file, and save safe metadata.',
      metric: 'LOCK',
    },
  ],
};
